### PR TITLE
Add example initializer to be copied to projects

### LINKED ISSUE #42: Why does the project not support  non intrusive mode？
Why does perftools/php-profiler not  support non intrusive type,such as  using auto_ prepend_file to introduce the component? Thank you!

### PR DESCRIPTION
**Pull request by glensc**
Perhaps we still need some file to be added to auto_prepend_file config.

Fixes: https://github.com/perftools/php-profiler/issues/42

### CODE REVIEW

**Comment by glensc** [comment]
@perftools/maintainers: Should this example file be complete with all configuration options? or should this file be minimal and pointing to documentation?

a fine balance between maintainability (duplication) and usability for the end-users.

In other words, should we but more effort into having good defaults, or rather have it copied out every bit that can be configured.

**Comment by markstory** [comment]
> Should this example file be complete with all configuration options? or should this file be minimal and pointing to documentation?

I would do all configuration and include the documentation in the example file. Then the docs could link to the current source file.

**Comment by glensc** [comment]
There's also defaults in the source itself:
- https://github.com/perftools/php-profiler/blob/0.14.0/src/Profiler.php#L269-L292

**Review by markstory — APPROVED** [review]

**Comment by glensc** [comment]
Updated, something like this then?

**Comment by glensc** [comment]
There's still duplication in readme file, becase moving them to one big file made imho it unreadable

**Pull request merged**
